parameters:
  input-folder:
    testing101
  namespace:
    knbtest
  optional:
    - -v
    - --debug
  output-folder:
    "./testing101/plots"
  kubeconfig-file:
    "/afs/cern.ch/user/f/fkatulsk/private/FKatulskiOpenStack.conf"
